### ISSUE TITLE
What is to enter when asked for "'Enter the code from that page here: '"

### ISSUE THREAD

**Issue by AshishDekate** [googlecodelabs/slides-api#4]

**Comment by grant** [comment]
Enter the code given from the linked website.

**Comment by AshishDekate** [comment]
Sorry, but I could not understand by linked website. Can you please elaborate?

**Comment by grant** [comment]
Please provide more steps in what went wrong. 
> _No description provided._
Following the steps of running the codelab should give the code you're looking for.

**Comment by AshishDekate** [comment]
It asks to enter code as per below lines.

rl.question('**Enter the code from that page here**: ', (code) => {
      rl.close();

**Comment by AshishDekate** [comment]
Finally I used OAuth 2.0 playground to get authorization code and generated token manually using same.

**Comment by ABHISHEKSHAH56** [comment]
hey when authentication complted then its redirect to your redirect url !!
just check the parms of url you will find the code!!
like http://localhost:53951/?**code=4/0AY0e-g6VHLYeYHLkT4Lj-gJ_D94AwA0oHxU4lK3pQbTT8QdBnWdSTHNRAUqsgPgWb6nhbw**&scope=https://www.googleapis.com/auth/classroom.courses.readonly
